<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Payments-Portal.Data\Payments-Portal.Data.csproj" />
    <ProjectReference Include="..\Payments-Portal.Service\Payments-Portal.Service.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Payments_Portal.API</RootNamespace>
  </PropertyGroup>

</Project>
